### ISSUE TITLE
Way to add settings

### ISSUE THREAD

**Issue by kasvith** [octopusdownloader/octopusdownloader#36]
# Description
We need a way to use settings

# Roadmap

- [x] Introduce a Proxy class for settings
- [x] Persist and Load settings from files
- [ ] Add UI/UX

**Comment by namila007** [comment]
#45

**Comment by namila007** [comment]
#67 close
